### ISSUE TITLE
Password in config

### ISSUE THREAD

**Issue by gwsii** [Nordstrom/artillery-plugin-influxdb#1]
Provide an alternative to a plain text password in the config file:
* secure S3 location
* hash + KMS solution

**Comment by erikerikson** [comment]
Or, as a middle step, taken from environment variables.

**Comment by gwsii** [comment]
Agree, that's a good quick fix!

How about INFLUX_USERNAME and INFLUX_PASSWORD?

Did a quick Google search and they don't see to collide with any predefined Influx names.

**Comment by gwsii** [comment]
Fixed! :)
