### ISSUE TITLE
Thows an exception if latency value is NaN

### ISSUE THREAD

**Issue by trondhindenes** [Nordstrom/artillery-plugin-influxdb#5]
Artillery records NaN for urls it csnnot reach or other types of errors. This plugin should check for this before it attempts to insert data into influxdb.

**Comment by erikerikson** [comment]
Hi @trondhindenes.  Is the issue that the plugin sends NaN to influx and influx chokes on that or do you get a stack trace from the plugin in the case of a NaN latency value?  Is artillery literally reporting something like the following?
```
[
  1476705156737,
  "c9faee5d-206f-4054-94fe-1d0b8cdb9103",
  NaN,
  302
],
```
